from app.schemas.parser import TransactionCategory

TRANSACTION_CATEGORIES: tuple[TransactionCategory, ...] = (
    "transportasi",
    "makanan_minuman",
    "tagihan",
    "tempat_tinggal",
    "belanja",
    "hiburan",
    "utang_cicilan",
    "pendapatan",
    "kesehatan",
    "pendidikan",
    "keluarga",
    "lainnya",
)

CATEGORY_KEYWORDS: dict[TransactionCategory, tuple[str, ...]] = {
    "transportasi": (
        "transportasi",
        "ongkos",
        "ongkir",
        "parkir",
        "valet",
        "tol",
        "e toll",
        "e-toll",
        "etoll",
        "jasa marga",
        "bensin",
        "bbm",
        "pertalite",
        "pertamax",
        "solar",
        "shell",
        "bp akr",
        "spbu",
        "grab",
        "grab bike",
        "grabbike",
        "grab car",
        "grabcar",
        "gojek",
        "goride",
        "go ride",
        "gocar",
        "go car",
        "ojol",
        "ojek online",
        "ojek",
        "maxim",
        "indrive",
        "in drive",
        "bluebird",
        "blue bird",
        "taksi",
        "taxi",
        "angkot",
        "mikrolet",
        "bus",
        "busway",
        "transjakarta",
        "krl",
        "commuter line",
        "commuter",
        "kereta",
        "kai",
        "mrt",
        "lrt",
        "travel",
        "shuttle",
        "tiket bus",
        "tiket kereta",
        "tiket pesawat",
        "pesawat",
        "kapal",
        "tambal ban",
        "cuci motor",
        "cuci mobil",
        "servis motor",
        "service motor",
        "servis mobil",
        "service mobil",
    ),
    "makanan_minuman": (
        "makanan",
        "makan",
        "makan pagi",
        "makan siang",
        "makan malam",
        "sarapan",
        "lunch",
        "dinner",
        "brunch",
        "minuman",
        "minum",
        "jajan",
        "jajanan",
        "snack",
        "cemilan",
        "ngemil",
        "kopi",
        "ngopi",
        "coffee",
        "kafe",
        "cafe",
        "restoran",
        "restaurant",
        "warteg",
        "warung",
        "kantin",
        "gofood",
        "go food",
        "grabfood",
        "grab food",
        "shopeefood",
        "shopee food",
        "nasi",
        "nasi padang",
        "nasi goreng",
        "ayam",
        "ayam geprek",
        "ayam goreng",
        "bakso",
        "mie",
        "mi",
        "mie ayam",
        "soto",
        "sate",
        "seblak",
        "martabak",
        "roti",
        "donat",
        "boba",
        "es kopi",
        "es teh",
        "aqua",
        "air mineral",
        "susu",
        "teh",
        "jus",
        "buah",
        "sayur",
        "beras",
        "telur",
        "minyak goreng",
        "gula",
        "garam",
        "sembako",
        "kfc",
        "mcd",
        "mcdonald",
        "hokben",
        "solaria",
        "starbucks",
        "janji jiwa",
        "kopi kenangan",
    ),
    "tagihan": (
        "tagihan",
        "bill",
        "iuran",
        "langganan",
        "listrik",
        "token listrik",
        "pln",
        "air",
        "pdam",
        "internet",
        "wifi",
        "wi-fi",
        "indihome",
        "first media",
        "biznet",
        "myrepublic",
        "iconnet",
        "oxygen",
        "pulsa",
        "paket data",
        "data internet",
        "kuota",
        "telkomsel",
        "xl",
        "axis",
        "indosat",
        "im3",
        "tri",
        "three",
        "smartfren",
        "byu",
        "by.u",
        "pascabayar",
        "postpaid",
        "listrik pascabayar",
        "telepon",
        "telpon",
        "pajak",
        "pbb",
        "stnk",
        "pajak motor",
        "pajak mobil",
        "ipl",
        "maintenance fee",
        "iuran rt",
        "iuran rw",
        "admin bank",
        "biaya admin",
        "biaya layanan",
        "materai",
    ),
    "tempat_tinggal": (
        "tempat tinggal",
        "rumah",
        "kos",
        "kost",
        "indekos",
        "kontrakan",
        "sewa rumah",
        "sewa kamar",
        "sewa apartemen",
        "apartemen",
        "apartment",
        "rent",
        "deposit rumah",
        "deposit kos",
        "renovasi",
        "perbaikan rumah",
        "tukang",
        "perabot",
        "furniture",
        "alat rumah",
        "peralatan rumah",
        "gas",
        "gas elpiji",
        "elpiji",
        "galon",
        "isi galon",
        "aqua galon",
        "laundry",
        "cuci baju",
        "sabun cuci",
        "deterjen",
        "detergen",
        "kebersihan rumah",
        "art",
        "asisten rumah tangga",
    ),
    "belanja": (
        "belanja",
        "shopping",
        "shoping",
        "beli barang",
        "checkout",
        "check out",
        "cod",
        "online shop",
        "olshop",
        "marketplace",
        "tokopedia",
        "shopee",
        "lazada",
        "blibli",
        "bukalapak",
        "tiktok shop",
        "tiktokshop",
        "zalora",
        "alfamart",
        "indomaret",
        "alfagift",
        "alfamidi",
        "supermarket",
        "minimarket",
        "hypermart",
        "transmart",
        "carrefour",
        "lottemart",
        "pakaian",
        "baju",
        "kaos",
        "kemeja",
        "celana",
        "jaket",
        "sepatu",
        "sandal",
        "tas",
        "dompet",
        "jam tangan",
        "kosmetik",
        "skincare",
        "makeup",
        "parfum",
        "haircut",
        "potong rambut",
        "barber",
        "salon",
        "gadget",
        "elektronik",
        "hp",
        "handphone",
        "laptop",
        "charger",
        "earphone",
        "aksesoris",
        "stationery",
        "alat tulis",
        "mainan",
    ),
    "hiburan": (
        "hiburan",
        "entertainment",
        "bioskop",
        "nonton",
        "cinema",
        "movie",
        "netflix",
        "disney",
        "disney hotstar",
        "spotify",
        "youtube premium",
        "viu",
        "vidio",
        "prime video",
        "game",
        "gaming",
        "topup game",
        "top up game",
        "steam",
        "playstation",
        "psn",
        "xbox",
        "nintendo",
        "mobile legends",
        "mlbb",
        "pubg",
        "valorant",
        "roblox",
        "konser",
        "festival",
        "karaoke",
        "billiard",
        "biliar",
        "liburan",
        "jalan jalan",
        "jalan-jalan",
        "healing",
        "rekreasi",
        "wisata",
        "tiket wisata",
        "hotel",
        "villa",
        "staycation",
        "nongkrong",
        "gym",
        "fitness",
    ),
    "utang_cicilan": (
        "utang",
        "hutang",
        "bayar utang",
        "bayar hutang",
        "cicilan",
        "nyicil",
        "mencicil",
        "angsuran",
        "bayar angsuran",
        "kredit",
        "pinjaman",
        "pinjem",
        "minjem",
        "pinjaman online",
        "pinjol",
        "p2p lending",
        "lpbbti",
        "paylater",
        "bnpl",
        "buy now pay later",
        "spaylater",
        "shopee paylater",
        "gopaylater",
        "gopay paylater",
        "gopay later",
        "traveloka paylater",
        "ovo paylater",
        "kredivo",
        "akulaku",
        "indodana",
        "home credit",
        "homecredit",
        "julo",
        "easycash",
        "kredit pintar",
        "adakami",
        "ada kami",
        "rupiah cepat",
        "pinjam duit",
        "spinjaman",
        "shopee pinjam",
        "danamas",
        "modalku",
        "amartha",
        "investree",
        "koinworks",
        "gadai",
        "pegadaian",
        "kasbon",
        "talangan",
        "kpr",
        "kta",
        "kredit tanpa agunan",
        "kredit motor",
        "kredit mobil",
        "leasing",
        "baf",
        "adira",
        "fif",
        "fifgroup",
        "wom finance",
        "mega finance",
        "kartu kredit",
        "cc",
        "tagihan cc",
        "bayar cc",
        "minimum payment",
        "minpay",
        "jatuh tempo",
        "denda",
        "bunga pinjaman",
        "loan",
        "debt",
    ),
    "pendapatan": (
        "pendapatan",
        "pemasukan",
        "income",
        "gaji",
        "gajian",
        "salary",
        "payroll",
        "bonus",
        "thr",
        "tunjangan",
        "insentif",
        "komisi",
        "freelance",
        "fee freelance",
        "honor",
        "honorarium",
        "upah",
        "bayaran",
        "transfer masuk",
        "uang masuk",
        "dana masuk",
        "saldo masuk",
        "hasil jualan",
        "hasil dagang",
        "jualan",
        "profit",
        "refund",
        "reimburse",
        "reimbursement",
        "cashback",
        "dividen",
        "bunga tabungan",
        "uang saku",
        "hadiah",
        "dikasih",
        "cair",
    ),
    "kesehatan": (
        "kesehatan",
        "dokter",
        "obat",
        "obat-obatan",
        "apotek",
        "apotik",
        "rumah sakit",
        "rs",
        "klinik",
        "puskesmas",
        "medical",
        "checkup",
        "check up",
        "tes lab",
        "laboratorium",
        "vaksin",
        "vitamin",
        "suplemen",
        "bpjs kesehatan",
        "asuransi kesehatan",
        "terapi",
        "fisioterapi",
        "psikolog",
        "psikiater",
        "konsultasi dokter",
        "dokter gigi",
        "gigi",
        "dental",
        "kacamata",
        "softlens",
        "optik",
        "optical",
        "masker",
        "antigen",
        "pcr",
    ),
    "pendidikan": (
        "pendidikan",
        "sekolah",
        "kuliah",
        "kampus",
        "spp",
        "ukt",
        "uang sekolah",
        "uang kuliah",
        "biaya sekolah",
        "biaya kuliah",
        "kursus",
        "course",
        "training",
        "pelatihan",
        "bootcamp",
        "les",
        "bimbel",
        "guru les",
        "buku",
        "modul",
        "ebook",
        "seminar",
        "webinar",
        "workshop",
        "sertifikasi",
        "ujian",
        "biaya ujian",
        "udemy",
        "coursera",
        "skillshare",
        "kelas online",
    ),
    "keluarga": (
        "keluarga",
        "anak",
        "istri",
        "suami",
        "orang tua",
        "ortu",
        "ayah",
        "ibu",
        "bapak",
        "mama",
        "papa",
        "adik",
        "kakak",
        "saudara",
        "nenek",
        "kakek",
        "mertua",
        "nafkah",
        "uang belanja rumah",
        "uang dapur",
        "uang jajan anak",
        "kirim ibu",
        "kirim ortu",
        "transfer ibu",
        "transfer ortu",
        "arisan",
        "kondangan",
        "amplop",
        "kado",
        "hadiah ulang tahun",
        "zakat",
        "sedekah",
        "infak",
        "infaq",
        "donasi",
        "sumbangan",
    ),
}
