from app.schemas.parser import TransactionCategory

TRANSACTION_CATEGORIES: tuple[TransactionCategory, ...] = (
    "transportasi",
    "makanan_minuman",
    "tagihan",
    "tempat_tinggal",
    "belanja",
    "hiburan",
    "utang_cicilan",
    "pendapatan",
    "kesehatan",
    "pendidikan",
    "keluarga",
    "lainnya",
)

CATEGORY_KEYWORDS: dict[TransactionCategory, tuple[str, ...]] = {
    "transportasi": (
        "parkir",
        "bensin",
        "grab",
        "gojek",
        "tol",
        "ojek",
        "taksi",
        "angkot",
        "bus",
        "kereta",
        "mrt",
        "lrt",
    ),
    "makanan_minuman": (
        "makan",
        "kopi",
        "restoran",
        "nasi",
        "minum",
        "jajan",
        "sarapan",
        "siang",
        "malam",
        "bakso",
        "mie",
        "ayam",
    ),
    "tagihan": (
        "listrik",
        "air",
        "internet",
        "pulsa",
        "token",
        "wifi",
        "pdam",
        "pln",
    ),
    "tempat_tinggal": ("kos", "kontrakan", "sewa", "apartemen", "rumah"),
    "belanja": (
        "belanja",
        "supermarket",
        "alfamart",
        "indomaret",
        "tokopedia",
        "shopee",
        "lazada",
    ),
    "hiburan": ("bioskop", "netflix", "spotify", "game", "konser", "liburan"),
    "utang_cicilan": ("cicilan", "utang", "pinjaman", "bayar utang"),
    "pendapatan": ("gaji", "bonus", "freelance", "transfer masuk", "pendapatan"),
    "kesehatan": ("dokter", "obat", "apotek", "rumah sakit", "klinik"),
    "pendidikan": ("sekolah", "kursus", "buku", "kuliah", "training"),
    "keluarga": ("anak", "istri", "suami", "orang tua", "keluarga"),
}
