-- Registration tokens: invite tokens that let unregistered users self-register
-- via the Telegram bot.  Generated by the admin with /token and claimed by
-- users sending the token in chat after /start.

create table if not exists registration_tokens (
  id uuid primary key default gen_random_uuid(),

  token text not null unique,             -- canonical form: XXXX-XXXX-XXXX (Crockford Base32)

  created_by_telegram_id bigint,          -- admin who generated the token (audit)
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,         -- mandatory expiry (default 30 days from creation)

  claimed_at timestamptz,                  -- null until claimed
  claimed_by_telegram_id bigint,           -- the telegram user id who claimed it
  claimed_user_id uuid references users(id) on delete set null,

  status text not null default 'active'
    check (status in ('active', 'claimed', 'expired'))
);

create index if not exists idx_registration_tokens_token
  on registration_tokens (token);
create index if not exists idx_registration_tokens_status_expires
  on registration_tokens (status, expires_at);

alter table registration_tokens enable row level security;
revoke all on table registration_tokens from public, anon, authenticated;

-- Atomic token claim: validates the token, inserts a new user, and marks the
-- token as claimed in a single transaction.  Mirrors the
-- claim_expired_conversation_states RPC pattern used by the advisor-mode job.
create or replace function public.claim_registration_token(
  p_token text,
  p_telegram_user_id bigint,
  p_telegram_username text,
  p_language_code text default 'id',
  p_currency text default 'IDR',
  p_timezone text default 'Asia/Jakarta'
) returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_token record;
  v_user public.users%rowtype;
  v_existing_user public.users%rowtype;
  v_normalized text;
begin
  -- Normalize: uppercase and strip hyphens/spaces so matching is tolerant.
  v_normalized := upper(replace(replace(btrim(p_token), '-', ''), ' ', ''));

  select * from public.registration_tokens
    where upper(replace(replace(btrim(token), '-', ''), ' ', '')) = v_normalized
    for update
    into v_token;

  if not found then
    return jsonb_build_object('ok', false, 'error', 'not_found');
  end if;

  if v_token.status = 'claimed' or v_token.claimed_at is not null then
    return jsonb_build_object('ok', false, 'error', 'already_claimed');
  end if;

  if v_token.expires_at < now() then
    update public.registration_tokens set status = 'expired' where id = v_token.id;
    return jsonb_build_object('ok', false, 'error', 'expired');
  end if;

  select * from public.users
    where telegram_user_id = p_telegram_user_id
    for update
    into v_existing_user;

  if found and v_existing_user.status = 'active' then
    return jsonb_build_object('ok', false, 'error', 'already_registered');
  end if;

  if found then
    update public.users
      set telegram_username = p_telegram_username,
          status = 'active',
          onboarding_status = 'pending',
          language_code = p_language_code,
          currency = p_currency,
          timezone = p_timezone,
          registered_by_telegram_id = v_token.created_by_telegram_id,
          registered_at = now(),
          unregistered_at = null
      where id = v_existing_user.id
      returning * into v_user;
  else
    insert into public.users (
      telegram_user_id, telegram_username, role, status, onboarding_status,
      language_code, currency, timezone,
      registered_by_telegram_id, registered_at
    ) values (
      p_telegram_user_id, p_telegram_username, 'user', 'active', 'pending',
      p_language_code, p_currency, p_timezone,
      v_token.created_by_telegram_id, now()
    ) returning * into v_user;
  end if;

  update public.registration_tokens
    set status = 'claimed',
        claimed_at = now(),
        claimed_by_telegram_id = p_telegram_user_id,
        claimed_user_id = v_user.id
    where id = v_token.id;

  return jsonb_build_object('ok', true, 'user_id', v_user.id::text);
end;
$$;

revoke all on function public.claim_registration_token(text, bigint, text, text, text, text)
  from public, anon, authenticated;
grant execute on function public.claim_registration_token(text, bigint, text, text, text, text)
  to service_role;

-- Mark expired tokens: called by the dedicated cron job to flip unclaimed,
-- past-expiry tokens from 'active' to 'expired' so they stop appearing in
-- active lookups.
create or replace function public.mark_expired_registration_tokens(
  p_limit integer default 200
) returns integer
language sql
security definer
set search_path = ''
as $$
  with candidates as (
    select id
    from public.registration_tokens
    where status = 'active'
      and expires_at < now()
      and claimed_at is null
    order by expires_at
    limit p_limit
    for update skip locked
  ),
  expired as (
    update public.registration_tokens tokens
    set status = 'expired'
    from candidates
    where tokens.id = candidates.id
    returning tokens.id
  )
  select count(*)::integer from expired;
$$;

revoke all on function public.mark_expired_registration_tokens(integer)
  from public, anon, authenticated;
grant execute on function public.mark_expired_registration_tokens(integer)
  to service_role;